FOV=90
# baseline 10 epoch
CUDA_VISIBLE_DEVICES=0 nohup python tool_multi_fov_clip_rotate_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_contrastive_dcn3_rotate.yaml' --sample 1 --rotate --x 3 --y 3 --z 180 --fov $FOV --resume 'perspect_resize_clip_mask_checkpoints_dcn3_constrastive_rotate_final/ControlNet-epoch=20-global_step=108464.0.bak.ckpt' --save-path 'finalexp_img_log/clip_contrastivee_dcn_rotate_sgag_fov90_33180_epoch20_image_log' >gen_ours_epoch20_all_1.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python tool_multi_fov_clip_rotate_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_contrastive_dcn3_rotate.yaml' --sample 2 --rotate --x 3 --y 3 --z 180 --fov $FOV --resume 'perspect_resize_clip_mask_checkpoints_dcn3_constrastive_rotate_final/ControlNet-epoch=20-global_step=108464.0.bak.ckpt' --save-path 'finalexp_img_log/clip_contrastivee_dcn_rotate_sgag_fov90_33180_epoch20_image_log' >gen_ours_epoch20_all_2.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python tool_multi_fov_clip_rotate_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_contrastive_dcn3_rotate.yaml' --sample 3 --rotate --x 3 --y 3 --z 180 --fov $FOV --resume 'perspect_resize_clip_mask_checkpoints_dcn3_constrastive_rotate_final/ControlNet-epoch=20-global_step=108464.0.bak.ckpt' --save-path 'finalexp_img_log/clip_contrastivee_dcn_rotate_sgag_fov90_33180_epoch20_image_log' >gen_ours_epoch20_all_3.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python tool_multi_fov_clip_rotate_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_contrastive_dcn3_rotate.yaml' --sample 4 --rotate --x 3 --y 3 --z 180 --fov $FOV --resume 'perspect_resize_clip_mask_checkpoints_dcn3_constrastive_rotate_final/ControlNet-epoch=20-global_step=108464.0.bak.ckpt' --save-path 'finalexp_img_log/clip_contrastivee_dcn_rotate_sgag_fov90_33180_epoch20_image_log' >gen_ours_epoch20_all_4.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python tool_multi_fov_clip_rotate_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_contrastive_dcn3_rotate.yaml' --sample 5 --rotate --x 3 --y 3 --z 180 --fov $FOV --resume 'perspect_resize_clip_mask_checkpoints_dcn3_constrastive_rotate_final/ControlNet-epoch=20-global_step=108464.0.bak.ckpt' --save-path 'finalexp_img_log/clip_contrastivee_dcn_rotate_sgag_fov90_33180_epoch20_image_log' >gen_ours_epoch20_all_5.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python tool_multi_fov_clip_rotate_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_contrastive_dcn3_rotate.yaml' --sample 6 --rotate --x 3 --y 3 --z 180 --fov $FOV --resume 'perspect_resize_clip_mask_checkpoints_dcn3_constrastive_rotate_final/ControlNet-epoch=20-global_step=108464.0.bak.ckpt' --save-path 'finalexp_img_log/clip_contrastivee_dcn_rotate_sgag_fov90_33180_epoch20_image_log' >gen_ours_epoch20_all_6.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python tool_multi_fov_clip_rotate_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_contrastive_dcn3_rotate.yaml' --sample 7 --rotate --x 3 --y 3 --z 180 --fov $FOV --resume 'perspect_resize_clip_mask_checkpoints_dcn3_constrastive_rotate_final/ControlNet-epoch=20-global_step=108464.0.bak.ckpt' --save-path 'finalexp_img_log/clip_contrastivee_dcn_rotate_sgag_fov90_33180_epoch20_image_log' >gen_ours_epoch20_all_7.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python tool_multi_fov_clip_rotate_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_contrastive_dcn3_rotate.yaml' --sample 8 --rotate --x 3 --y 3 --z 180 --fov $FOV --resume 'perspect_resize_clip_mask_checkpoints_dcn3_constrastive_rotate_final/ControlNet-epoch=20-global_step=108464.0.bak.ckpt' --save-path 'finalexp_img_log/clip_contrastivee_dcn_rotate_sgag_fov90_33180_epoch20_image_log' >gen_ours_epoch20_all_8.log 2>&1 &