# baseline 16 epoch
FOV=30
CUDA_VISIBLE_DEVICES=0 nohup python multi_low_fov_mask2img.py --config-file 'models/cldm_v15.yaml' --sample 1 --fov $FOV --resume 'baseline_final_checkpoints/ControlNet-epoch=15-global_step=55087.0.ckpt' --save-path 'finalexp_img_log/baseline_fov30_epoch20_image_log' >gen_baseline_epoch20_all_1.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python multi_low_fov_mask2img.py --config-file 'models/cldm_v15.yaml' --sample 2 --fov $FOV --resume 'baseline_final_checkpoints/ControlNet-epoch=15-global_step=55087.0.ckpt' --save-path 'finalexp_img_log/baseline_fov30_epoch20_image_log' >gen_baseline_epoch20_all_2.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python multi_low_fov_mask2img.py --config-file 'models/cldm_v15.yaml' --sample 3 --fov $FOV --resume 'baseline_final_checkpoints/ControlNet-epoch=15-global_step=55087.0.ckpt' --save-path 'finalexp_img_log/baseline_fov30_epoch20_image_log' >gen_baseline_epoch20_all_3.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python multi_low_fov_mask2img.py --config-file 'models/cldm_v15.yaml' --sample 4 --fov $FOV --resume 'baseline_final_checkpoints/ControlNet-epoch=15-global_step=55087.0.ckpt' --save-path 'finalexp_img_log/baseline_fov30_epoch20_image_log' >gen_baseline_epoch20_all_4.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python multi_low_fov_mask2img.py --config-file 'models/cldm_v15.yaml' --sample 5 --fov $FOV --resume 'baseline_final_checkpoints/ControlNet-epoch=15-global_step=55087.0.ckpt' --save-path 'finalexp_img_log/baseline_fov30_epoch20_image_log' >gen_baseline_epoch20_all_5.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python multi_low_fov_mask2img.py --config-file 'models/cldm_v15.yaml' --sample 6 --fov $FOV --resume 'baseline_final_checkpoints/ControlNet-epoch=15-global_step=55087.0.ckpt' --save-path 'finalexp_img_log/baseline_fov30_epoch20_image_log' >gen_baseline_epoch20_all_6.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python multi_low_fov_mask2img.py --config-file 'models/cldm_v15.yaml' --sample 7 --fov $FOV --resume 'baseline_final_checkpoints/ControlNet-epoch=15-global_step=55087.0.ckpt' --save-path 'finalexp_img_log/baseline_fov30_epoch20_image_log' >gen_baseline_epoch20_all_7.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python multi_low_fov_mask2img.py --config-file 'models/cldm_v15.yaml' --sample 8 --fov $FOV --resume 'baseline_final_checkpoints/ControlNet-epoch=15-global_step=55087.0.ckpt' --save-path 'finalexp_img_log/baseline_fov30_epoch20_image_log' >gen_baseline_epoch20_all_8.log 2>&1 &