FOV=90
# baseline 10 epoch
CUDA_VISIBLE_DEVICES=0 nohup python tool_multi_fov_clip_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_dcn3.yaml' --sample 1 --fov $FOV --resume 'ablation_checkpoints/clip_dcn_new_resume/ControlNet-epoch=20-global_step=72302.0.ckpt' --save-path 'finalexp_img_log/clip_dcn_fov90_epoch20_image_log' >gen_clip_dcn_all_1.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python tool_multi_fov_clip_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_dcn3.yaml' --sample 2 --fov $FOV --resume 'ablation_checkpoints/clip_dcn_new_resume/ControlNet-epoch=20-global_step=72302.0.ckpt' --save-path 'finalexp_img_log/clip_dcn_fov90_epoch20_image_log' >gen_clip_dcn_all_2.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python tool_multi_fov_clip_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_dcn3.yaml' --sample 3 --fov $FOV --resume 'ablation_checkpoints/clip_dcn_new_resume/ControlNet-epoch=20-global_step=72302.0.ckpt' --save-path 'finalexp_img_log/clip_dcn_fov90_epoch20_image_log' >gen_clip_dcn_all_3.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python tool_multi_fov_clip_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_dcn3.yaml' --sample 4 --fov $FOV --resume 'ablation_checkpoints/clip_dcn_new_resume/ControlNet-epoch=20-global_step=72302.0.ckpt' --save-path 'finalexp_img_log/clip_dcn_fov90_epoch20_image_log' >gen_clip_dcn_all_4.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python tool_multi_fov_clip_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_dcn3.yaml' --sample 5 --fov $FOV --resume 'ablation_checkpoints/clip_dcn_new_resume/ControlNet-epoch=20-global_step=72302.0.ckpt' --save-path 'finalexp_img_log/clip_dcn_fov90_epoch20_image_log' >gen_clip_dcn_all_5.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python tool_multi_fov_clip_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_dcn3.yaml' --sample 6 --fov $FOV --resume 'ablation_checkpoints/clip_dcn_new_resume/ControlNet-epoch=20-global_step=72302.0.ckpt' --save-path 'finalexp_img_log/clip_dcn_fov90_epoch20_image_log' >gen_clip_dcn_all_6.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python tool_multi_fov_clip_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_dcn3.yaml' --sample 7 --fov $FOV --resume 'ablation_checkpoints/clip_dcn_new_resume/ControlNet-epoch=20-global_step=72302.0.ckpt' --save-path 'finalexp_img_log/clip_dcn_fov90_epoch20_image_log' >gen_clip_dcn_all_7.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python tool_multi_fov_clip_mask2img.py --config-file 'models/cldm_v15_clip_new_resize_dcn3.yaml' --sample 8 --fov $FOV --resume 'ablation_checkpoints/clip_dcn_new_resume/ControlNet-epoch=20-global_step=72302.0.ckpt' --save-path 'finalexp_img_log/clip_dcn_fov90_epoch20_image_log' >gen_clip_dcn_all_8.log 2>&1 &